// Confetti preset configurations for Pixel Banner
// Each preset defines default parameters for a specific visual effect

export const CONFETTI_PRESETS = {
    snow: {
        count: 1,
        size: 0.7,
        speed: 0,
        gravity: 0.5,
        spread: 0,
        drift: 0,
        duration: 400,
        delay: 0,
        fadeIn: 500,
        opacity: 0.8,
        continuous: true,
        interval: 100,
        position: 'top',
        colors: ['#ffffff'],
        shapes: ['circle'],
        emoji: null,
        originSpread: 'random',
        sizeRange: [0.1, 0.5],
        gravityRange: [0.4, 0.6],
        driftRange: [-0.4, 0.4]
    },
    snowflakes: {
        count: 1,
        size: 0.7,
        speed: 0,
        gravity: 0.1,
        spread: 1,
        drift: 0,
        duration: 1000,
        delay: 0,
        fadeIn: 500,
        opacity: 0.7,
        continuous: true,
        interval: 600,
        position: 'top',
        startY: -0.1,
        colors: ['#afc7d9', '#4cb3cd'],
        customShapes: ['snowflake'],
        originSpread: 'random',
        sizeRange: [1, 3],
        gravityRange: [0.1, 0.4],
        driftRange: [-0.4, 0.4]
    },

    leaves: {
        count: 1,
        size: 2.0,
        speed: 0,
        gravity: 0.3,
        spread: 0,
        drift: 0,
        duration: 600,
        delay: 0,
        fadeIn: 500,
        opacity: 0.9,
        continuous: true,
        interval: 350,
        position: 'top',
        colors: ['#e74c3c', '#e67e22', '#f39c12', '#d35400', '#c0392b'],
        customShapes: ['leaf'],
        flat: false,
        originSpread: 'random',
        sizeRange: [1, 2],
        gravityRange: [0.2, 0.4],
        driftRange: [-1.0, 1.0]
    },

    rain_light: {
        count: 1,
        size: 0.5,
        speed: 0,
        gravity: 2.0,
        spread: 0,
        drift: 0,
        duration: 200,
        delay: 0,
        fadeIn: 350,
        opacity: 0.6,
        continuous: true,
        interval: 400,
        position: 'top',
        startY: -0.1,
        colors: ['#1b78d4ff', '#aaccee'],
        customShapes: ['raindrop'],
        shapes: ['circle'],
        emoji: null,
        originSpread: 'random',
        sizeRange: [0.3, 0.6],
        gravityRange: [1.8, 2.2],
        driftRange: [0, 0]
    },
    rain_heavy: {
        count: 1,
        size: 0.5,
        speed: 0,
        gravity: 2.0,
        spread: 0,
        drift: 0,
        duration: 200,
        delay: 0,
        fadeIn: 300,
        opacity: 1,
        continuous: true,
        interval: 150,
        position: 'top',
        colors: ['#1b78d4ff', '#aaccee'],
        customShapes: ['raindrop'],
        flat: true,
        emoji: null,
        originSpread: 'random',
        sizeRange: [0.3, 0.6],
        gravityRange: [1.8, 2.2],
        driftRange: [0, 0]
    },

    space: {
        count: 1,
        size: 0.4,
        speed: 0,
        gravity: 0,
        spread: 0,
        drift: 3.0,
        duration: 800,
        delay: 0,
        fadeIn: 1000,
        opacity: 0.7,
        continuous: true,
        interval: 124,
        position: 'left',
        startY: 0,
        colors: ['#ffffff', '#ffffcc', '#fffacd'],
        shapes: ['circle'],
        emoji: null,
        originSpread: 'random',
        sizeRange: [0.1, 0.4],
        gravityRange: [-0.05, 0.05],
        driftRange: [2.0, 4.0]
    },
    aliens: {
        count: 1,
        size: 0.4,
        speed: 0,
        gravity: 0,
        spread: 0,
        drift: 3.0,
        duration: 800,
        delay: 0,
        fadeIn: 1000,
        opacity: 0.7,
        continuous: true,
        interval: 700,
        position: 'left',
        startY: 0,
        colors: ['#ffffff', '#49c05dff'],
        customShapes: ['alien', 'ufo'],
        emoji: null,
        flat: true,
        originSpread: 'random',
        sizeRange: [1, 2.75],
        gravityRange: [-0.05, 0.05],
        driftRange: [1.0, 4.0]
    },

    fireworks: {
        count: 30,
        size: 0.85,
        speed: 20,
        gravity: 0.2,
        spread: 360,
        drift: 0,
        duration: 90,
        delay: 0,
        fadeIn: 0,
        opacity: 1.0,
        continuous: true,
        interval: 2500,
        position: 'random',
        colors: ['#ff000042', '#3e8a3eb7', '#008cff9d', '#ffff00b7', '#ff660098', '#00ffff7e', '#ffa600b2', '#ffffffb0'],
        shapes: ['star'],
        emoji: null,
        originSpread: 'random'
    },

    confetti: {
        count: 80,
        size: 1.0,
        speed: 55,
        gravity: 1.0,
        spread: 200,
        drift: 0,
        duration: 200,
        delay: 0,
        fadeIn: 0,
        opacity: 0.8,
        continuous: true,
        interval: 7000,
        position: 'center',
        colors: ['#e74c3c', '#3498db', '#2ecc71', '#f39c12', '#9b59b6', '#1abc9c', '#e67e22'],
        emoji: null,
        originSpread: 'fixed'
    },

    hearts: {
        count: 10,
        size: 2.0,
        speed: 30,
        gravity: -0.5,
        spread: 280,
        drift: 0.8,
        duration: 500,
        delay: 0,
        fadeIn: 500,
        opacity: 0.9,
        continuous: true,
        interval: 5000,
        position: 'random',
        colors: ['#e74c3c'],
        emoji: '❤️💕💖',
        originSpread: 'random',
        sizeRange: [1.5, 3],
        gravityRange: [-0.05, 0.05],
        driftRange: [0.5, 1.2]
    },

    sparkles: {
        count: 1,
        size: 0.7,
        speed: 15,
        gravity: 0.1,
        spread: 1000,
        drift: 0.1,
        duration: 400,
        delay: 0,
        fadeIn: 500,
        opacity: 0.75,
        continuous: true,
        interval: 400,
        position: 'random',
        colors: ['#ffd700', '#c0c0c0', '#ffffff'],
        emoji: '✨',
        originSpread: 'random',
        driftRange: [-4, 4],
        sizeRange: [0.5, 1],
        speedRange: [3, 11]
    },

    pop_rocks: {
        count: 1,
        size: 0.7,
        speed: 15,
        gravity: 0.1,
        spread: 1000,
        drift: 0.1,
        duration: 400,
        delay: 0,
        fadeIn: 500,
        opacity: 0.75,
        continuous: true,
        interval: 400,
        position: 'random',
        colors: ['#ffd700', '#c0c0c0', '#ffffff'],
        emoji: '🔴🟠🟡🟢🔵🟣',
        originSpread: 'random',
        driftRange: [-4, 4],
        sizeRange: [0.5, 1],
        speedRange: [3, 11]
    },

    crystals: {
        count: 1,
        size: 1.2,
        speed: 0,
        gravity: 0.3,
        spread: 0,
        drift: 0,
        duration: 600,
        delay: 0,
        fadeIn: 500,
        opacity: 0.8,
        continuous: true,
        interval: 300,
        position: 'random',
        colors: ['#e0115f', '#36bbf8ff', '#50c878', '#9966cc', '#ffc30b'],
        customShapes: ['gem', 'gem2', 'gem3', 'gem4', 'gem5'],
        flat: true,
        emoji: null,
        originSpread: 'random',
        sizeRange: [0.8, 2.5],
        gravityRange: [0.2, 0.4],
        driftRange: [-0.3, 0.3]
    },

    bubbles: {
        count: 35,
        size: 1.5,
        speed: 20,
        gravity: -0.8,
        spread: 180,
        drift: 0.5,
        duration: 500,
        delay: 0,
        fadeIn: 800,
        opacity: 0.5,
        continuous: true,
        interval: 1000,
        position: 'bottom',
        colors: ['#87ceeb', '#add8e6', '#b0e0e6'],
        emoji: null,
        originSpread: 'random'
    }
};

// Get list of all preset names
export function getPresetNames() {
    return Object.keys(CONFETTI_PRESETS);
}

// Get a specific preset configuration
export function getPreset(name) {
    return CONFETTI_PRESETS[name] || null;
}

// Get a copy of preset with deep clone to avoid mutations
export function getPresetCopy(name) {
    const preset = CONFETTI_PRESETS[name];
    if (!preset) return null;

    return {
        ...preset,
        colors: preset.colors ? [...preset.colors] : null,
        shapes: preset.shapes ? [...preset.shapes] : null,
        customShapes: preset.customShapes ? [...preset.customShapes] : null
    };
}
